# Author: Mohammad Nuruzzaman 
# Date: 26th January 2023

version: '3'
 
services:

  ml-engineering:
    image: data2ml/ml-engineering:latest
    container_name: ml-engineering-demo
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app